<?php

// Data functions (insert, update, delete, form) for table assignments

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function assignments_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('assignments');
	if(!$arrPerm[1]){
		return false;
	}

	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	$data['time_start'] = makeSafe($_REQUEST['time_start']);
		if($data['time_start'] == empty_lookup_value){ $data['time_start'] = ''; }
	$data['time_start'] = time24($data['time_start']);
	$data['time_end'] = makeSafe($_REQUEST['time_end']);
		if($data['time_end'] == empty_lookup_value){ $data['time_end'] = ''; }
	$data['time_end'] = time24($data['time_end']);
	$data['unit_code'] = makeSafe($_REQUEST['unit_code']);
		if($data['unit_code'] == empty_lookup_value){ $data['unit_code'] = ''; }
	$data['venue'] = makeSafe($_REQUEST['venue']);
		if($data['venue'] == empty_lookup_value){ $data['venue'] = ''; }
	$data['manager'] = makeSafe($_REQUEST['manager']);
		if($data['manager'] == empty_lookup_value){ $data['manager'] = ''; }
	$data['project'] = makeSafe($_REQUEST['project']);
		if($data['project'] == empty_lookup_value){ $data['project'] = ''; }
	$data['worker'] = makeSafe($_REQUEST['worker']);
		if($data['worker'] == empty_lookup_value){ $data['worker'] = ''; }
	if($data['date']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Date': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['time_start']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Time Start': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['time_end']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Time End': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['unit_code']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Unit code': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['venue']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Venue': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['manager']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Manager': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['project']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Project': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['worker']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Worker': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: assignments_before_insert
	if(function_exists('assignments_before_insert')){
		$args=array();
		if(!assignments_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `assignments` set       `date`=' . (($data['date'] !== '' && $data['date'] !== NULL) ? "'{$data['date']}'" : 'NULL') . ', `time_start`=' . (($data['time_start'] !== '' && $data['time_start'] !== NULL) ? "'{$data['time_start']}'" : 'NULL') . ', `time_end`=' . (($data['time_end'] !== '' && $data['time_end'] !== NULL) ? "'{$data['time_end']}'" : 'NULL') . ', `unit_code`=' . (($data['unit_code'] !== '' && $data['unit_code'] !== NULL) ? "'{$data['unit_code']}'" : 'NULL') . ', `venue`=' . (($data['venue'] !== '' && $data['venue'] !== NULL) ? "'{$data['venue']}'" : 'NULL') . ', `manager`=' . (($data['manager'] !== '' && $data['manager'] !== NULL) ? "'{$data['manager']}'" : 'NULL') . ', `project`=' . (($data['project'] !== '' && $data['project'] !== NULL) ? "'{$data['project']}'" : 'NULL') . ', `worker`=' . (($data['worker'] !== '' && $data['worker'] !== NULL) ? "'{$data['worker']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"assignments_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: assignments_after_insert
	if(function_exists('assignments_after_insert')){
		$res = sql("select * from `assignments` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!assignments_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('assignments', $recID, getLoggedMemberID());

	return $recID;
}

function assignments_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('assignments');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='assignments' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='assignments' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: assignments_before_delete
	if(function_exists('assignments_before_delete')){
		$args=array();
		if(!assignments_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `assignments` where `id`='$selected_id'", $eo);

	// hook: assignments_after_delete
	if(function_exists('assignments_after_delete')){
		$args=array();
		assignments_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='assignments' and pkValue='$selected_id'", $eo);
}

function assignments_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('assignments');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='assignments' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='assignments' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	if($data['date']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Date': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['time_start'] = makeSafe($_REQUEST['time_start']);
		if($data['time_start'] == empty_lookup_value){ $data['time_start'] = ''; }
	$data['time_start'] = time24($data['time_start']);
	if($data['time_start']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Time Start': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['time_end'] = makeSafe($_REQUEST['time_end']);
		if($data['time_end'] == empty_lookup_value){ $data['time_end'] = ''; }
	$data['time_end'] = time24($data['time_end']);
	if($data['time_end']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Time End': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['unit_code'] = makeSafe($_REQUEST['unit_code']);
		if($data['unit_code'] == empty_lookup_value){ $data['unit_code'] = ''; }
	if($data['unit_code']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Unit code': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['venue'] = makeSafe($_REQUEST['venue']);
		if($data['venue'] == empty_lookup_value){ $data['venue'] = ''; }
	if($data['venue']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Venue': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['manager'] = makeSafe($_REQUEST['manager']);
		if($data['manager'] == empty_lookup_value){ $data['manager'] = ''; }
	if($data['manager']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Manager': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['project'] = makeSafe($_REQUEST['project']);
		if($data['project'] == empty_lookup_value){ $data['project'] = ''; }
	if($data['project']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Project': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['worker'] = makeSafe($_REQUEST['worker']);
		if($data['worker'] == empty_lookup_value){ $data['worker'] = ''; }
	if($data['worker']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Worker': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: assignments_before_update
	if(function_exists('assignments_before_update')){
		$args=array();
		if(!assignments_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `assignments` set       `date`=' . (($data['date'] !== '' && $data['date'] !== NULL) ? "'{$data['date']}'" : 'NULL') . ', `time_start`=' . (($data['time_start'] !== '' && $data['time_start'] !== NULL) ? "'{$data['time_start']}'" : 'NULL') . ', `time_end`=' . (($data['time_end'] !== '' && $data['time_end'] !== NULL) ? "'{$data['time_end']}'" : 'NULL') . ', `unit_code`=' . (($data['unit_code'] !== '' && $data['unit_code'] !== NULL) ? "'{$data['unit_code']}'" : 'NULL') . ', `venue`=' . (($data['venue'] !== '' && $data['venue'] !== NULL) ? "'{$data['venue']}'" : 'NULL') . ', `manager`=' . (($data['manager'] !== '' && $data['manager'] !== NULL) ? "'{$data['manager']}'" : 'NULL') . ', `project`=' . (($data['project'] !== '' && $data['project'] !== NULL) ? "'{$data['project']}'" : 'NULL') . ', `worker`=' . (($data['worker'] !== '' && $data['worker'] !== NULL) ? "'{$data['worker']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="assignments_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: assignments_after_update
	if(function_exists('assignments_after_update')){
		$res = sql("SELECT * FROM `assignments` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!assignments_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='assignments' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function assignments_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('assignments');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_manager = thisOr(undo_magic_quotes($_REQUEST['filterer_manager']), '');
	$filterer_project = thisOr(undo_magic_quotes($_REQUEST['filterer_project']), '');

	// populate filterers, starting from children to grand-parents
	if($filterer_project && !$filterer_manager) $filterer_manager = sqlValue("select manager from projects where id='" . makeSafe($filterer_project) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: manager
	$combo_manager = new DataCombo;
	// combobox: project, filterable by: manager
	$combo_project = new DataCombo;
	// combobox: worker
	$combo_worker = new Combo;
	$combo_worker->ListType = 0;
	$combo_worker->MultipleSeparator = ', ';
	$combo_worker->ListBoxHeight = 10;
	$combo_worker->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/assignments.worker.csv')){
		$worker_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/assignments.worker.csv')));
		$combo_worker->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($worker_data)));
		$combo_worker->ListData = $combo_worker->ListItem;
	}else{
		$combo_worker->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("1;;2;;3;;4;;5;;6")));
		$combo_worker->ListData = $combo_worker->ListItem;
	}
	$combo_worker->SelectName = 'worker';
	$combo_worker->AllowNull = false;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='assignments' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='assignments' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `assignments` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'assignments_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_date->DefaultDate = $row['date'];
		$combo_manager->SelectedData = $row['manager'];
		$combo_project->SelectedData = $row['project'];
		$combo_worker->SelectedData = $row['worker'];
	}else{
		$combo_manager->SelectedData = $filterer_manager;
		$combo_project->SelectedData = $filterer_project;
		$combo_worker->SelectedText = ( $_REQUEST['FilterField'][1]=='9' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
	}
	$combo_manager->HTML = '<span id="manager-container' . $rnd1 . '"></span><input type="hidden" name="manager" id="manager' . $rnd1 . '" value="' . html_attr($combo_manager->SelectedData) . '">';
	$combo_manager->MatchText = '<span id="manager-container-readonly' . $rnd1 . '"></span><input type="hidden" name="manager" id="manager' . $rnd1 . '" value="' . html_attr($combo_manager->SelectedData) . '">';
	$combo_project->HTML = '<span id="project-container' . $rnd1 . '"></span><input type="hidden" name="project" id="project' . $rnd1 . '" value="' . html_attr($combo_project->SelectedData) . '">';
	$combo_project->MatchText = '<span id="project-container-readonly' . $rnd1 . '"></span><input type="hidden" name="project" id="project' . $rnd1 . '" value="' . html_attr($combo_project->SelectedData) . '">';
	$combo_worker->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_manager__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['manager'] : $filterer_manager); ?>"};
		AppGini.current_project__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['project'] : $filterer_project); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(manager_reload__RAND__) == 'function') manager_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(project_reload__RAND__) == \'function\') project_reload__RAND__(AppGini.current_manager__RAND__.value);' : ''); ?>
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function manager_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#manager-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_manager__RAND__.value, t: 'assignments', f: 'manager' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="manager"]').val(resp.results[0].id);
							$j('[id=manager-container-readonly__RAND__]').html('<span id="manager-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=managers_view_parent]').hide(); }else{ $j('.btn[id=managers_view_parent]').show(); }

						if(typeof(project_reload__RAND__) == 'function') project_reload__RAND__(AppGini.current_manager__RAND__.value);

							if(typeof(manager_update_autofills__RAND__) == 'function') manager_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'assignments', f: 'manager' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_manager__RAND__.value = e.added.id;
				AppGini.current_manager__RAND__.text = e.added.text;
				$j('[name="manager"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=managers_view_parent]').hide(); }else{ $j('.btn[id=managers_view_parent]').show(); }

						if(typeof(project_reload__RAND__) == 'function') project_reload__RAND__(AppGini.current_manager__RAND__.value);

				if(typeof(manager_update_autofills__RAND__) == 'function') manager_update_autofills__RAND__();
			});

			if(!$j("#manager-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_manager__RAND__.value, t: 'assignments', f: 'manager' },
					success: function(resp){
						$j('[name="manager"]').val(resp.results[0].id);
						$j('[id=manager-container-readonly__RAND__]').html('<span id="manager-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=managers_view_parent]').hide(); }else{ $j('.btn[id=managers_view_parent]').show(); }

						if(typeof(manager_update_autofills__RAND__) == 'function') manager_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_manager__RAND__.value, t: 'assignments', f: 'manager' },
				success: function(resp){
					$j('[id=manager-container__RAND__], [id=manager-container-readonly__RAND__]').html('<span id="manager-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=managers_view_parent]').hide(); }else{ $j('.btn[id=managers_view_parent]').show(); }

					if(typeof(manager_update_autofills__RAND__) == 'function') manager_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function project_reload__RAND__(filterer_manager){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#project-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_manager: filterer_manager, id: AppGini.current_project__RAND__.value, t: 'assignments', f: 'project' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="project"]').val(resp.results[0].id);
							$j('[id=project-container-readonly__RAND__]').html('<span id="project-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=projects_view_parent]').hide(); }else{ $j('.btn[id=projects_view_parent]').show(); }


							if(typeof(project_update_autofills__RAND__) == 'function') project_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { filterer_manager: filterer_manager, s: term, p: page, t: 'assignments', f: 'project' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_project__RAND__.value = e.added.id;
				AppGini.current_project__RAND__.text = e.added.text;
				$j('[name="project"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=projects_view_parent]').hide(); }else{ $j('.btn[id=projects_view_parent]').show(); }


				if(typeof(project_update_autofills__RAND__) == 'function') project_update_autofills__RAND__();
			});

			if(!$j("#project-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_project__RAND__.value, t: 'assignments', f: 'project' },
					success: function(resp){
						$j('[name="project"]').val(resp.results[0].id);
						$j('[id=project-container-readonly__RAND__]').html('<span id="project-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=projects_view_parent]').hide(); }else{ $j('.btn[id=projects_view_parent]').show(); }

						if(typeof(project_update_autofills__RAND__) == 'function') project_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_project__RAND__.value, t: 'assignments', f: 'project' },
				success: function(resp){
					$j('[id=project-container__RAND__], [id=project-container-readonly__RAND__]').html('<span id="project-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=projects_view_parent]').hide(); }else{ $j('.btn[id=projects_view_parent]').show(); }

					if(typeof(project_update_autofills__RAND__) == 'function') project_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/assignments_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/assignments_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Assignments details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return assignments_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return assignments_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return assignments_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#time_start').replaceWith('<div class=\"form-control-static\" id=\"time_start\">' + (jQuery('#time_start').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#time_end').replaceWith('<div class=\"form-control-static\" id=\"time_end\">' + (jQuery('#time_end').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#unit_code').replaceWith('<div class=\"form-control-static\" id=\"unit_code\">' + (jQuery('#unit_code').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#venue').replaceWith('<div class=\"form-control-static\" id=\"venue\">' + (jQuery('#venue').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#manager').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#manager_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#project').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#project_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#worker').replaceWith('<div class=\"form-control-static\" id=\"worker\">' + (jQuery('#worker').val() || '') + '</div>'); jQuery('#worker-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('#time_start').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: true, showInputs: false, disableFocus: true, minuteStep: 5 });";
		$jsEditable .= "\tjQuery('#time_end').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: true, showInputs: false, disableFocus: true, minuteStep: 5 });";
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : $combo_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(manager)%%>', $combo_manager->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(manager)%%>', $combo_manager->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(manager)%%>', urlencode($combo_manager->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(project)%%>', $combo_project->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(project)%%>', $combo_project->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(project)%%>', urlencode($combo_project->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(worker)%%>', $combo_worker->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(worker)%%>', $combo_worker->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'manager' => array('managers', 'Manager'), 'project' => array('projects', 'Project'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(time_start)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(time_end)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(unit_code)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(venue)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(manager)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(project)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(worker)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', @date('m/d/Y', @strtotime(html_attr($row['date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['date'])))), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_start)%%>', time12(html_attr($row['time_start'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_start)%%>', urlencode(time12($urow['time_start'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_end)%%>', time12(html_attr($row['time_end'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_end)%%>', urlencode(time12($urow['time_end'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(unit_code)%%>', safe_html($urow['unit_code']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(unit_code)%%>', html_attr($row['unit_code']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(unit_code)%%>', urlencode($urow['unit_code']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(venue)%%>', safe_html($urow['venue']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(venue)%%>', html_attr($row['venue']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(venue)%%>', urlencode($urow['venue']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(manager)%%>', safe_html($urow['manager']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(manager)%%>', html_attr($row['manager']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manager)%%>', urlencode($urow['manager']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(project)%%>', safe_html($urow['project']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(project)%%>', html_attr($row['project']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(project)%%>', urlencode($urow['project']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(worker)%%>', safe_html($urow['worker']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(worker)%%>', html_attr($row['worker']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(worker)%%>', urlencode($urow['worker']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_start)%%>', time12(''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_start)%%>', urlencode(time12('')), $templateCode);
		$templateCode = str_replace('<%%VALUE(time_end)%%>', time12(''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(time_end)%%>', urlencode(time12('')), $templateCode);
		$templateCode = str_replace('<%%VALUE(unit_code)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(unit_code)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(venue)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(venue)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(manager)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(manager)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(project)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(project)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(worker)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(worker)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('assignments');
	if($selected_id){
		$jdata = get_joined_record('assignments', $selected_id);
		if($jdata === false) $jdata = get_defaults('assignments');
		$rdata = $row;
	}
	$templateCode .= loadView('assignments-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: assignments_dv
	if(function_exists('assignments_dv')){
		$args=array();
		assignments_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>