<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'industries' => array(   
			),
			'categories' => array(   
				'manager' => array(   
					'parent-table' => 'industries',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Categories',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/chart_organisation.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Name', 2 => 'Industry'),
					'display-field-names' => array(1 => 'name', 2 => 'manager'),
					'sortable-fields' => array(0 => '`categories`.`id`', 1 => 2, 2 => '`industries1`.`name`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-categories',
					'template-printable' => 'children-categories-printable',
					'query' => "SELECT `categories`.`id` as 'id', `categories`.`name` as 'name', IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') as 'manager' FROM `categories` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`categories`.`manager` "
				)
			),
			'class_time_table' => array(   
				'manager' => array(   
					'parent-table' => 'industries',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Class time table',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/blackboard_drawing.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Day', 2 => ' Time Start', 3 => 'Time End', 4 => 'Unit code', 5 => 'Venue', 6 => 'Industry', 7 => 'Category', 8 => 'Proposal'),
					'display-field-names' => array(1 => 'day', 2 => 'time_start', 3 => 'time_end', 4 => 'unit_code', 5 => 'venue', 6 => 'manager', 7 => 'project', 8 => 'proposal'),
					'sortable-fields' => array(0 => '`class_time_table`.`id`', 1 => 2, 2 => '`class_time_table`.`time_start`', 3 => '`class_time_table`.`time_end`', 4 => 5, 5 => 6, 6 => '`industries1`.`name`', 7 => '`categories1`.`name`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-class_time_table',
					'template-printable' => 'children-class_time_table-printable',
					'query' => "SELECT `class_time_table`.`id` as 'id', `class_time_table`.`day` as 'day', TIME_FORMAT(`class_time_table`.`time_start`, '%r') as 'time_start', TIME_FORMAT(`class_time_table`.`time_end`, '%r') as 'time_end', `class_time_table`.`unit_code` as 'unit_code', `class_time_table`.`venue` as 'venue', IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') as 'manager', IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') as 'project', `class_time_table`.`proposal` as 'proposal' FROM `class_time_table` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`class_time_table`.`manager` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`class_time_table`.`project` "
				),
				'project' => array(   
					'parent-table' => 'categories',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Class time table',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/blackboard_drawing.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Day', 2 => ' Time Start', 3 => 'Time End', 4 => 'Unit code', 5 => 'Venue', 6 => 'Industry', 7 => 'Category', 8 => 'Proposal'),
					'display-field-names' => array(1 => 'day', 2 => 'time_start', 3 => 'time_end', 4 => 'unit_code', 5 => 'venue', 6 => 'manager', 7 => 'project', 8 => 'proposal'),
					'sortable-fields' => array(0 => '`class_time_table`.`id`', 1 => 2, 2 => '`class_time_table`.`time_start`', 3 => '`class_time_table`.`time_end`', 4 => 5, 5 => 6, 6 => '`industries1`.`name`', 7 => '`categories1`.`name`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-class_time_table',
					'template-printable' => 'children-class_time_table-printable',
					'query' => "SELECT `class_time_table`.`id` as 'id', `class_time_table`.`day` as 'day', TIME_FORMAT(`class_time_table`.`time_start`, '%r') as 'time_start', TIME_FORMAT(`class_time_table`.`time_end`, '%r') as 'time_end', `class_time_table`.`unit_code` as 'unit_code', `class_time_table`.`venue` as 'venue', IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') as 'manager', IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') as 'project', `class_time_table`.`proposal` as 'proposal' FROM `class_time_table` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`class_time_table`.`manager` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`class_time_table`.`project` "
				)
			),
			'assignments' => array(   
				'manager' => array(   
					'parent-table' => 'industries',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Assignments',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/books.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Date', 2 => 'Time Start', 3 => 'Time End', 4 => 'Unit code', 5 => 'Venue', 6 => 'Industry', 7 => 'Category', 8 => 'Proposal'),
					'display-field-names' => array(1 => 'date', 2 => 'time_start', 3 => 'time_end', 4 => 'unit_code', 5 => 'venue', 6 => 'manager', 7 => 'project', 8 => 'proposal'),
					'sortable-fields' => array(0 => '`assignments`.`id`', 1 => '`assignments`.`date`', 2 => '`assignments`.`time_start`', 3 => '`assignments`.`time_end`', 4 => 5, 5 => 6, 6 => '`industries1`.`name`', 7 => '`categories1`.`name`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-assignments',
					'template-printable' => 'children-assignments-printable',
					'query' => "SELECT `assignments`.`id` as 'id', if(`assignments`.`date`,date_format(`assignments`.`date`,'%m/%d/%Y'),'') as 'date', TIME_FORMAT(`assignments`.`time_start`, '%r') as 'time_start', TIME_FORMAT(`assignments`.`time_end`, '%r') as 'time_end', `assignments`.`unit_code` as 'unit_code', `assignments`.`venue` as 'venue', IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') as 'manager', IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') as 'project', `assignments`.`proposal` as 'proposal' FROM `assignments` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`assignments`.`manager` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`assignments`.`project` "
				),
				'project' => array(   
					'parent-table' => 'categories',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Assignments',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/books.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Date', 2 => 'Time Start', 3 => 'Time End', 4 => 'Unit code', 5 => 'Venue', 6 => 'Industry', 7 => 'Category', 8 => 'Proposal'),
					'display-field-names' => array(1 => 'date', 2 => 'time_start', 3 => 'time_end', 4 => 'unit_code', 5 => 'venue', 6 => 'manager', 7 => 'project', 8 => 'proposal'),
					'sortable-fields' => array(0 => '`assignments`.`id`', 1 => '`assignments`.`date`', 2 => '`assignments`.`time_start`', 3 => '`assignments`.`time_end`', 4 => 5, 5 => 6, 6 => '`industries1`.`name`', 7 => '`categories1`.`name`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-assignments',
					'template-printable' => 'children-assignments-printable',
					'query' => "SELECT `assignments`.`id` as 'id', if(`assignments`.`date`,date_format(`assignments`.`date`,'%m/%d/%Y'),'') as 'date', TIME_FORMAT(`assignments`.`time_start`, '%r') as 'time_start', TIME_FORMAT(`assignments`.`time_end`, '%r') as 'time_end', `assignments`.`unit_code` as 'unit_code', `assignments`.`venue` as 'venue', IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') as 'manager', IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') as 'project', `assignments`.`proposal` as 'proposal' FROM `assignments` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`assignments`.`manager` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`assignments`.`project` "
				)
			),
			'personal_time_table' => array(   
			),
			'student_details' => array(   
				'manager' => array(   
					'parent-table' => 'industries',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Personal details',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/administrator.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Full name', 2 => 'Industry', 3 => 'Category', 4 => 'Proposal', 5 => 'Reg no'),
					'display-field-names' => array(1 => 'full_name', 2 => 'manager', 3 => 'project', 4 => 'proposal', 5 => 'reg_no'),
					'sortable-fields' => array(0 => '`student_details`.`id`', 1 => 2, 2 => '`industries1`.`name`', 3 => '`categories1`.`name`', 4 => 5, 5 => 6),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-student_details',
					'template-printable' => 'children-student_details-printable',
					'query' => "SELECT `student_details`.`id` as 'id', `student_details`.`full_name` as 'full_name', IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') as 'manager', IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') as 'project', `student_details`.`proposal` as 'proposal', `student_details`.`reg_no` as 'reg_no' FROM `student_details` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`student_details`.`manager` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`student_details`.`project` "
				),
				'project' => array(   
					'parent-table' => 'categories',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Personal details',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/administrator.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Full name', 2 => 'Industry', 3 => 'Category', 4 => 'Proposal', 5 => 'Reg no'),
					'display-field-names' => array(1 => 'full_name', 2 => 'manager', 3 => 'project', 4 => 'proposal', 5 => 'reg_no'),
					'sortable-fields' => array(0 => '`student_details`.`id`', 1 => 2, 2 => '`industries1`.`name`', 3 => '`categories1`.`name`', 4 => 5, 5 => 6),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-student_details',
					'template-printable' => 'children-student_details-printable',
					'query' => "SELECT `student_details`.`id` as 'id', `student_details`.`full_name` as 'full_name', IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') as 'manager', IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') as 'project', `student_details`.`proposal` as 'proposal', `student_details`.`reg_no` as 'reg_no' FROM `student_details` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`student_details`.`manager` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`student_details`.`project` "
				)
			),
			'proposals' => array(   
			)
		);

	/*************************************/
	/* End of configuration */


	$currDir = dirname(__FILE__);
	include("{$currDir}/defaultLang.php");
	include("{$currDir}/language.php");
	include("{$currDir}/lib.php");
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags($_REQUEST['SelectedID']);
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children', 'get-records-printable', 'show-children-printable'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li%s><a href="#panel_%s-%s" id="tab_%s-%s" data-toggle="tab">%s%s</a></li>' . "\n\t\t\t\t\t",($tabLabels ? '' : ' class="active"'), $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="tab-pane%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? '' : ' active'), $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<button type="button" class="btn btn-default" data-target="#panel_%s-%s" id="tab_%s-%s" data-toggle="collapse">%s %s</button>' . "\n\t\t\t\t\t", $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="collapse"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records-printable" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable'){
				$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			$permChild = getTablePermissions($ChildTable);
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy] ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable'){
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template-printable'], $data);
			}else{
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
