<?php
// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/proposals.php");
	include("$currDir/proposals_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('proposals');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "proposals";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`proposals`.`id`" => "id",
		"`proposals`.`notice`" => "notice",
		"IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') /* Industry */" => "manager",
		"IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') /* Category */" => "project",
		"`proposals`.`proposal`" => "proposal",
		"if(`proposals`.`date`,date_format(`proposals`.`date`,'%m/%d/%Y'),'')" => "date"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`proposals`.`id`',
		2 => 2,
		3 => '`industries1`.`name`',
		4 => '`categories1`.`name`',
		5 => 5,
		6 => '`proposals`.`date`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`proposals`.`id`" => "id",
		"`proposals`.`notice`" => "notice",
		"IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') /* Industry */" => "manager",
		"IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') /* Category */" => "project",
		"`proposals`.`proposal`" => "proposal",
		"if(`proposals`.`date`,date_format(`proposals`.`date`,'%m/%d/%Y'),'')" => "date"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`proposals`.`id`" => "ID",
		"`proposals`.`notice`" => "Description",
		"IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') /* Industry */" => "Industry",
		"IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') /* Category */" => "Category",
		"`proposals`.`proposal`" => "Proposal",
		"`proposals`.`date`" => "Date"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`proposals`.`id`" => "id",
		"`proposals`.`notice`" => "notice",
		"IF(    CHAR_LENGTH(`industries1`.`name`), CONCAT_WS('',   `industries1`.`name`), '') /* Industry */" => "manager",
		"IF(    CHAR_LENGTH(`categories1`.`name`), CONCAT_WS('',   `categories1`.`name`), '') /* Category */" => "project",
		"`proposals`.`proposal`" => "proposal",
		"if(`proposals`.`date`,date_format(`proposals`.`date`,'%m/%d/%Y'),'')" => "date"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'manager' => 'Industry', 'project' => 'Category');

	$x->QueryFrom = "`proposals` LEFT JOIN `industries` as industries1 ON `industries1`.`id`=`proposals`.`manager` LEFT JOIN `categories` as categories1 ON `categories1`.`id`=`proposals`.`project` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "proposals_view.php";
	$x->RedirectAfterInsert = "proposals_view.php?SelectedID=#ID#";
	$x->TableTitle = "Proposals";
	$x->TableIcon = "resources/table_icons/clipboard_empty.png";
	$x->PrimaryKey = "`proposals`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("Description", "Industry", "Category", "Proposal", "Date");
	$x->ColFieldName = array('notice', 'manager', 'project', 'proposal', 'date');
	$x->ColNumber  = array(2, 3, 4, 5, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/proposals_templateTV.html';
	$x->SelectedTemplate = 'templates/proposals_templateTVS.html';
	$x->TemplateDV = 'templates/proposals_templateDV.html';
	$x->TemplateDVP = 'templates/proposals_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `proposals`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='proposals' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `proposals`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='proposals' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`proposals`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: proposals_init
	$render=TRUE;
	if(function_exists('proposals_init')){
		$args=array();
		$render=proposals_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: proposals_header
	$headerCode='';
	if(function_exists('proposals_header')){
		$args=array();
		$headerCode=proposals_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: proposals_footer
	$footerCode='';
	if(function_exists('proposals_footer')){
		$args=array();
		$footerCode=proposals_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>